# Generated by Django 4.2.9 on 2026-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="hook_script_file",
            field=models.FileField(
                blank=True,
                help_text="上传Python脚本文件",
                null=True,
                upload_to="hook_scripts/",
                verbose_name="Hook脚本文件",
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="max_message_count",
            field=models.IntegerField(
                default=100,
                help_text="保留的最大消息数量（1-1000）",
                verbose_name="最大消息记录数",
            ),
        ),
    ]
