# Generated by Django 4.2.9 on 2026-01-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_hook_script_file_robot_max_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='log_data',
            field=models.JSONField(blank=True, help_text='记录请求和响应的详细参数', null=True, verbose_name='日志数据'),
        ),
    ]
